version: 1.0.{build}
os: Visual Studio 2015
test: off
clone_folder: C:\projects\DirectionalFieldSynthesis
branches:
  only:
    - master
install:
  - git submodule update --init --recursive
  - cinstall: python
build_script:
  - echo Running cmake...
  - cd c:\projects\DirectionalFieldSynthesis\demos\2-sampling
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=Debug /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% 2-sampling.sln
  - cd c:\projects\DirectionalFieldSynthesis\demos\3-visualization
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=Debug /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% 3-visualization.sln
  - cd c:\projects\DirectionalFieldSynthesis\demos\4-live-coding
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=Debug /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% 4-live-coding.sln
